// n = order of flow; 2 = elliptic; 3 = triangular; ...
void plotRealVsSTEG(int n, int cent_min, int cent_max)
{
   bool plotflattened = true;

   char* realFName = Form("/home/palmerjh/CMSSW_5_3_20/STEGEff/cent_%d-%d_v%d_STEG_run182798_hiGeneralAndPixelTracks_v0.root",cent_min,cent_max,n);

   char* STEGFName = Form("/home/palmerjh/CMSSW_5_3_20/STEGEff/v%d_dataFromSTEG.root",n);

   // load Input File generated by STEG
   TFile * realFile = new TFile(realFName);
   TFile * STEGFile = new TFile(STEGFName);

   // load file with STEG input functions
   TFile * STEGFunctionFile = new TFile("/home/palmerjh/CMSSW_5_3_20/STEGEff/STEGFunctions.root");

   // Get the graphs and histograms from the file
   TGraph * STEGCorRU = &((*((TGraph*)STEGFile->Get(Form("v%d_Corrected_RU",n)))).Clone());
   TGraph * STEGCorGU = &((*((TGraph*)STEGFile->Get(Form("v%d_Corrected_GU",n)))).Clone());
   TGraph * STEGCorRF = &((*((TGraph*)STEGFile->Get(Form("v%d_Corrected_RF",n)))).Clone());
   TGraph * STEGCorGF = &((*((TGraph*)STEGFile->Get(Form("v%d_Corrected_GF",n)))).Clone());
   TGraph * STEGObsRU = &((*((TGraph*)STEGFile->Get(Form("v%d_Observed_RU",n)))).Clone());
   TGraph * STEGObsGU = &((*((TGraph*)STEGFile->Get(Form("v%d_Observed_GU",n)))).Clone());
   TGraph * STEGObsRF = &((*((TGraph*)STEGFile->Get(Form("v%d_Observed_RF",n)))).Clone());
   TGraph * STEGObsGF = &((*((TGraph*)STEGFile->Get(Form("v%d_Observed_GF",n)))).Clone());
   TGraph * realCorRU = &((*((TGraph*)realFile->Get(Form("v%d_Corrected_RU",n)))).Clone());
   TGraph * realCorRF = &((*((TGraph*)realFile->Get(Form("v%d_Corrected_RF",n)))).Clone());
   TGraph * realObsRU = &((*((TGraph*)realFile->Get(Form("v%d_Corrected_RU",n)))).Clone());
   TGraph * realObsRF = &((*((TGraph*)realFile->Get(Form("v%d_Corrected_RF",n)))).Clone());

   /*TH1F * planeAFlat = f->Get("planeAFlat");
   TH1F * planeBFlat = f->Get("planeBFlat");
   TH1F * planeCFlat = f->Get("planeCFlat");
   TH1F * planeAUnflat = f->Get("planeAUnflat");
   TH1F * planeBUnflat = f->Get("planeBUnflat");
   TH1F * planeCUnflat = f->Get("planeCUnflat");*/

   
   //f.Close();

   TCanvas * cVn = new TCanvas("cVn","cVn",1000,1000);
   cVn->cd();
   TH1F * hDum = new TH1F("hDum",Form(";p_{T} [GeV/c];v_{%d}",n),10,0,10);
   hDum->SetMinimum(-0.05);
   hDum->SetMaximum(0.2);
   hDum->GetYaxis()->CenterTitle();
   hDum->GetXaxis()->CenterTitle();
   hDum->Draw("AXIS");

   TF1 *VnvsPt = (TF1*) STEGFunctionFile->Get(Form("V%dvsPt",n));
   VnvsPt->SetLineColor(kBlack);
   VnvsPt->Draw("SAME");

   STEGCorRU->SetMarkerStyle(29);
   STEGCorRU->SetLineColor(kGreen);
   STEGCorRU->SetMarkerColor(kGreen);
   STEGCorRU->Draw("p");

   STEGCorGU->SetMarkerStyle(33);
   STEGCorGU->SetLineColor(kRed);
   STEGCorGU->SetMarkerColor(kRed);
   STEGCorGU->Draw("p");

   realCorRU->SetMarkerStyle(20);
   realCorRU->SetLineColor(kBlue);
   realCorRU->SetMarkerColor(kBlue);
   realCorRU->Draw("p");
 
   //testCorrection->Draw("ap");
   TLegend * leg = new TLegend(.3,.7,.9,.9);
   leg->SetFillColor(0);
   leg->AddEntry(STEGCorRU,Form("STEG_Reco_Unflattened_v_{%d}^{cor}\{EP+ & EP-\}",n),"lp");
   leg->AddEntry(STEGCorGU,Form("STEG_Gen_Unflattened_v_{%d}^{cor}\{EP+ & EP-\}",n),"lp");
   leg->AddEntry(realCorRU,Form("Real_Cent=%d-%d_Reco_Unflattened_v_{%d}^{cor}\{EP+ & EP-\}",cent_min,cent_max,n),"lp");
   leg->AddEntry(VnvsPt,Form("STEG_Input_Function_v_{%d}",n),"lp");
   leg->SetTextFont(63);
   leg->SetTextSize(17);
   leg->Draw();

   //STEGFile->Close();
   //realFile->Close();

   //STEGFunctionFile->Close();

   //if (plotHist) {
  
   /*TCanvas * cPhi = new TCanvas("cPhi","cPhi",600,600);
   cPhi->cd();
   cout << "cd okay" << endl;
   phiA->Draw();
   cout << "A okay" << endl;
   phiB->Draw("same");
   cout << "B okay" << endl;
   phiC->Draw("same");
   cout << "C okay" << endl;
   
   TCanvas * cPlaneA = new TCanvas("cPlaneA","cPlaneA",600,600);
   cPlaneA->cd();
   
    planeAFlat->Draw();
    planeAUnflat->Draw("same");

   TCanvas * cPlaneB = new TCanvas("cPlaneB","cPlaneB",600,600);
   cPlaneB->cd();

   planeBFlat->Draw();
   planeBUnflat->Draw("same");

   TCanvas * cPlaneC = new TCanvas("cPlaneC","cPlaneC",600,600);
   cPlaneC->cd();

   planeCFlat->Draw();
   planeCUnflat->Draw("same");

   //}*/


}
