// n = order of flow; 2 = elliptic; 3 = triangular; ...
void readHist(int n, int cent_min, int cent_max)
{
   // load Input File generated by STEG
   TFile f(Form("cent_%d-%d_v%d_STEG_run182798_hiGeneralAndPixelTracks_v0.root",cent_min,cent_max,n));

   // Get the graphs and histograms from the file
   TGraph * obsA = f.Get(Form("v%d_ObsA",n));
   TGraph * corA = f.Get(Form("v%d_CorrectedA",n));

   TGraph * obsB = f.Get(Form("v%d_ObsB",n));
   TGraph * corB = f.Get(Form("v%d_CorrectedB",n));

   TH1F * phiA = f.Get("phiA");
   TH1F * phiB = f.Get("phiB");
   TH1F * phiVn = f.Get("phiVn");
   TH1F * planeA = f.Get("planeA");
   TH1F * planeB = f.Get("planeB");
   
   f.Close();

   TCanvas * c1 = new TCanvas("c1","c1",600,600);
   c1->cd();
   TH1F * hDum = new TH1F("hDum",Form(";p_{T} [GeV/c];v_{%d}",n),10,0,10);
   hDum->SetMinimum(-0.05);
   hDum->SetMaximum(0.15);
   hDum->GetYaxis()->CenterTitle();
   hDum->GetXaxis()->CenterTitle();
   hDum->Draw();


   obsA->SetMarkerStyle(20);
   obsA->SetLineColor(kGreen);
   obsA->SetMarkerColor(kGreen);
   obsA->Draw("p");

   corA->SetMarkerStyle(20);
   corA->SetLineColor(kRed);
   corA->SetMarkerColor(kRed);
   corA->Draw("p");
 
   obsB->SetMarkerStyle(20);
   obsB->SetLineColor(kOrange);
   obsB->SetMarkerColor(kOrange);
   obsB->Draw("p");

   corB->SetMarkerStyle(20);
   corB->SetLineColor(kBlack);
   corB->SetMarkerColor(kBlack);
   corB->Draw("p");
   //testCorrection->Draw("ap");
   TLegend * leg = new TLegend(.7,.7,.9,.9);
   leg->SetFillColor(0);
   leg->AddEntry(obsA,Form("v_{%d}^{obs}\{EPA\}",n),"lp");
   leg->AddEntry(corA,Form("v_{%d}\{EPA\}",n),"lp");
   leg->AddEntry(obsB,Form("v_{%d}^{obs}\{EPB\}",n),"lp");
   leg->AddEntry(corB,Form("v_{%d}\{EPB\}",n),"lp");
   leg->Draw();
  
   TCanvas * c2 = new TCanvas("c2","c2",600,600);
   c2->cd();
   
   phiA->Draw();
   phiB->Draw();
   phiVn->Draw();
   
   TCanvas * c3 = new TCanvas("c3","c3",600,600);
   c3->cd();
   
   planeA->Draw();
   planeB->Draw();


}
