{
   // load Input File generated by STEG
   TFile f("testCluster.root");

   // Get the tree from the file
   TTree * steg = f.Get("tree");

   // Setup branches to read events from the tree
   int max_particles = 1000;
   Int_t np; // number of particles in the event
   Float_t phi[max_particles]; // arrays for the kinematics
   Float_t eta[max_particles]; // of each particle
   Float_t pt[max_particles];  // in the event

   // total number of events
   Int_t nevent = (Int_t) steg->GetEntries();
  
   // Here the TTree object is given the memory addresses
   // of our variables above as places to put the contents
   // of each branch when the "GetEntry" method is called
   steg->SetBranchAddress("npg",&np);
   steg->SetBranchAddress("phig",&phi);
   steg->SetBranchAddress("etag",&eta);
   steg->SetBranchAddress("ptg",&pt);

   // Set up a histogram to store some values
   TH1D * hdemo = new TH1D("hdemo",";#phi_{lab};counts",50,0,6.2831853);

   // Loop over the events in the tree
   for( Int_t i=0; i<nevent; i++)
   {
     // print a message every 100 events
     if( i%100 == 0) cout << "Processing event " << i << "...\n"; 

     // Load the information from event i
     steg->GetEntry(i);

     //Loop over all particles in the event
     for( Int_t j=0; j < np; j++)
     {
        // Fill our histogram with the phi of 
        // each particle, but only for particles 
        // with |eta|<1.0 and pT > 0.4
        if( pt[j] > 0.4 || fabs(eta[j]) < 1.0 )
          hdemo->Fill(phi[j]);
     }

   }

   // Now draw the histogram
   hdemo->Draw();

}    
